INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (1,'Jeffrey','Haskovec','jeffrey@test.com','Generic description','1234','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (2,'Chase','Koehler','chase@test.com','Generic description','password','New Sharon, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (3,'John','Ruby','john@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (4,'Thomas','Stackhouse','thomas@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (5,'TestFirst5','TestLast5','test5@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (6,'TestFirst6','TestLast6','test6@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (7,'TestFirst7','TestLast7','test7@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (8,'TestFirst8','TestLast8','test8@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (9,'TestFirst9','TestLast9','test9@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (10,'TestFirst10','TestLast10','test10@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (11,'TestFirst11','TestLast11','test11@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (12,'TestFirst12','TestLast12','test12@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (13,'TestFirst13','TestLast13','test13@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (14,'TestFirst14','TestLast14','test14@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (15,'TestFirst15','TestLast15','test15@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (16,'TestFirst16','TestLast16','test16@test.com','Generic description','password','Ames, IA');
INSERT INTO user(id, first_name, last_name, email, description, password, current_city) values (17,'TestFirst17','TestLast17','test17@test.com','Generic description','password','Ames, IA');